services:
  web-static:
    build:
        ../step1/apache-php-image
    ports:
      - "8080:80"
  web-dynamic:
    build:
        ../step2/express-image
    ports:
      - "8081:3000"
    image: "node"